"use client";
import{useState}from"react";import{ArrowRight,Check,FlaskConical,Ruler,Scale,Table2,Timer}from"lucide-react";import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{Feedback,Numeric}from"./Learning";import{density,round}from"@/lib/physics";import type{ProgressState}from"./types";
const tools=[["ruler","Vizore",Ruler,true],["scale","Peshore",Scale,true],["cylinder","Cilindër",FlaskConical,true],["timer","Kronometër",Timer,false],["table","Tabela",Table2,true]]as const;
export function Finale({p,save,navigate}:{p:ProgressState;save:(m:string,d:number)=>void;navigate:(x:string)=>void}){const[step,setStep]=useState(p.finaleResult?8:0);const[selected,setSelected]=useState<string[]>([]);const[tip,setTip]=useState("");const[dims,setDims]=useState(["","",""]);const[readings,setReadings]=useState<number[]>([]);const[suspect,setSuspect]=useState(0);const[vol,setVol]=useState(false);const[avg,setAvg]=useState(false);const[den,setDen]=useState(false);const[mat,setMat]=useState("");const d=round(density(97,36),2);const confirm=()=>{if(tools.filter(x=>x[3]).every(x=>selected.includes(x[0])))setStep(1);else setTip("Na duhet të masim dimensionet, masën, vëllimin dhe të ruajmë të dhënat.")};const dimDone=dims.join()==="4.2,3.1,2.8";const add=()=>setReadings([96.8,130.5,97.2].slice(0,readings.length+1));return <section className="finale"><header><button onClick={()=>navigate("map")}>← Harta</button><b>MISIONI FINAL · OBJEKTI 00-X</b><h1>Identifiko objektin misterioz</h1><p>Ke një objekt, instrumentet dhe të dhënat që do të mbledhësh.</p><div>{Array.from({length:8},(_,n)=><span className={step>n?"done":step===n?"on":""} key={n}>{step>n?<Check/>:n+1}</span>)}</div></header>
{step===0&&<Stage n="01 · PLANIFIKO" title="Çfarë duhet të dimë?"><p>Jo çdo mjet është i nevojshëm.</p><div className="tool-select">{tools.map(x=>{const I=x[2];return <button className={selected.includes(x[0])?"on":""} key={x[0]} onClick={()=>setSelected(z=>z.includes(x[0])?z.filter(y=>y!==x[0]):[...z,x[0]])}><I/><b>{x[1]}</b></button>})}</div><Button onClick={confirm}>Konfirmo mjetet</Button>{tip&&<Feedback>{tip}</Feedback>}</Stage>}
{step===1&&<Stage n="02 · MAT DIMENSIONET" title="Vendose objektin pranë vizores"><div className="dim-object">?<i>4.2 cm</i><i>3.1 cm</i><i>2.8 cm</i></div><div className="dim-inputs">{["Gjatësia","Gjerësia","Lartësia"].map((x,n)=><label key={x}>{x}<span><Input value={dims[n]} onChange={e=>{const z=[...dims];z[n]=e.target.value.replace(",",".");setDims(z)}}/> cm</span></label>)}</div>{dimDone?<Button onClick={()=>setStep(2)}>Ruaj <ArrowRight/></Button>:dims.some(Boolean)&&<Feedback>Lexo tri shenjat dhe shëno njësinë.</Feedback>}</Stage>}
{step===2&&<Stage n="03 · PËRSËRIT MATJEN" title="Mat masën tri herë"><div className="final-scale"><i>?</i><b>{readings.length?readings.at(-1)!.toFixed(1):"0.0"} g</b></div><Button onClick={add} disabled={readings.length===3}>{readings.length?"Mat përsëri":"Fillo matjen"}</Button><div className="readings">{[0,1,2].map(n=><span key={n}>MATJA {n+1}<b>{readings[n]?readings[n]+" g":"—"}</b></span>)}</div>{readings.length===3&&<><Feedback>Njëra matje duket shumë ndryshe. Kontrolloje.</Feedback><Button onClick={()=>setStep(3)}>Analizo <ArrowRight/></Button></>}</Stage>}
{step===3&&<Stage n="04 · KONTROLLO" title="Cila matje është e dyshimtë?"><div className="suspects">{readings.map(x=><button className={suspect===x?"on":""} key={x} onClick={()=>setSuspect(x)}>{x} g</button>)}</div>{suspect>0&&<Feedback ok={suspect===130.5}>{suspect===130.5?"Po. Peshorja nuk ishte zerojuar.":"Cilat dy matje janë afër?"}</Feedback>}{suspect===130.5&&<Button onClick={()=>setStep(4)}>Vazhdo <ArrowRight/></Button>}</Stage>}
{step===4&&<Stage n="05 · MAT VËLLIMIN" title="Përdor zhvendosjen e ujit"><div className="two-cyl"><article><span>PARA</span><i style={{height:"50%"}}/><b>50 ml</b></article><ArrowRight/><article><span>PAS</span><i style={{height:"86%"}}/><b>86 ml</b></article></div><Numeric label="Vëllimi i objektit" answer={36} unit="ml" hints={["Mos lexo vetëm fundin.","Gjej 86 − 50.","86 − 50 = 36 ml."]} onCorrect={()=>setVol(true)}/>{vol&&<Button onClick={()=>setStep(5)}>Ruaj vëllimin</Button>}</Stage>}
{step===5&&<Stage n="06 · PËRMBLIDH" title="Gjej masën mesatare"><p>Përdor 96.8 g dhe 97.2 g. Matja e dyshimtë u përjashtua pas kontrollit.</p><Numeric label="Masa mesatare" answer={97} unit="g" hints={["Mblidh dy matjet.","Shuma është 194.","194 ÷ 2 = 97 g."]} onCorrect={()=>setAvg(true)}/>{avg&&<Button onClick={()=>setStep(6)}>Llogarit densitetin</Button>}</Stage>}
{step===6&&<Stage n="07 · LLOGARIT" title="Masa 97 g dhe vëllimi 36 cm³"><div className="final-formula"><span>97 g</span>÷<span>36 cm³</span>=<span>{den?d+" g/cm³":"?"}</span></div><Numeric label="Densiteti" answer={d} unit="g/cm³" hints={["Përdor ρ = m/V.","Pjesëto 97 me 36.","Rezultati është 2.69."]} onCorrect={()=>setDen(true)}/>{den&&<Button onClick={()=>setStep(7)}>Krahaso materialet</Button>}</Stage>}
{step===7&&<Stage n="08 · PËRFUNDO" title="Cili material është më afër 2.69?"><div className="final-materials">{[["Dru",.7],["Plastikë",1.1],["Alumin",2.7],["Hekur",7.8]].map(x=><button className={mat===x[0]?"on":""} key={x[0]} onClick={()=>setMat(String(x[0]))}><b>{x[0]}</b><span>{x[1]} g/cm³</span></button>)}</div>{mat&&<Feedback ok={mat==="Alumin"}>{mat==="Alumin"?"Përputhet me aluminin.":"Kërko vlerën më të afërt."}</Feedback>}{mat==="Alumin"&&<Button onClick={()=>{save("Alumin",d);setStep(8)}}>Jep përfundimin</Button>}</Stage>}
{step===8&&<section className="final-success"><span>🏆</span><b>MISIONI U PËRFUNDUA</b><h2>OBJEKTI U IDENTIFIKUA.</h2><strong>ALUMIN · ρ ≈ {p.finaleResult?.density||d} g/cm³</strong><p>Nuk e gjete duke hamendësuar. E gjete duke vëzhguar, matur, krahasuar, llogaritur dhe kontrolluar.</p><h3>Kështu punon fizika.</h3><i>✦ FIZIKANI I RI</i><Button onClick={()=>navigate("map")}>Kthehu në laborator</Button></section>}</section>}
function Stage({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="final-stage"><b>{n}</b><h2>{title}</h2>{children}</section>}
