"use client";
import{useState}from"react";import{Beaker,Brain,Check,ChevronRight,Lightbulb,Sparkles}from"lucide-react";import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";
export function Prediction({question,options,value,onChoose}:{question:string;options:{value:string;label:string}[];value?:string;onChoose:(v:string)=>void}){return <section className="predict"><b><Sparkles/> PARASHIKO</b><h2>{question}</h2><p>Zgjidh para eksperimentit. Parashikimi yt ruhet.</p><div className="choices">{options.map(o=><Button key={o.value} variant={value===o.value?"default":"outline"} onClick={()=>onChoose(o.value)}>{value===o.value&&<Check/>}{o.label}</Button>)}</div>{value&&<small>✓ Parashikimi u ruajt. Tani eksperimento.</small>}</section>}
export function Feedback({children,ok=false}:{children:React.ReactNode;ok?:boolean}){return <div className={"feedback "+(ok?"ok":"")} role="status" aria-live="polite"><Lightbulb/><span>{children}</span></div>}
export function Curiosity({children}:{children:React.ReactNode}){return <div className="curiosity">🤔 <span>{children}</span></div>}
export function Phase({kind,children}:{kind:"ÇFARË NDODHI?"|"PSE NDODHI?"|"SI E QUAN FIZIKA?";children:React.ReactNode}){return <section className="inquiry-phase" data-kind={kind}><b>{kind}</b>{children}</section>}
export function ConceptReveal({name,children,formula,tone="lab"}:{name:string;children:React.ReactNode;formula?:React.ReactNode;tone?:"lab"|"dialog"|"grid"|"report"}){return <section className={"concept-reveal "+tone}><small>SI E QUAN FIZIKA?</small><h2>{name}</h2><p>{children}</p>{formula&&<strong>{formula}</strong>}</section>}
export function ExplainCheck({question,options,correct,onAnswer,tone="light"}:{question:string;options:string[];correct:string;onAnswer?:(ok:boolean)=>void;tone?:"light"|"dark"|"report"}){const[selected,setSelected]=useState("");const choose=(x:string)=>{setSelected(x);onAnswer?.(x===correct)};return <section className={"explain-check "+tone}><b><Brain/> A MUND TA SHPJEGOSH?</b><h3>{question}</h3><div>{options.map(x=><Button key={x} variant={selected===x?"default":"outline"} onClick={()=>choose(x)}>{x}</Button>)}</div>{selected&&<Feedback ok={selected===correct}>{selected===correct?"Po. Shpjegimi yt lidh atë që pe me arsyen fizike.":"Shiko përsëri çfarë ndryshoi dhe çfarë e shkaktoi."}</Feedback>}</section>}
export function BeforeContinue({question,answer,unit,meaning,meaningOptions,onPass}:{question:string;answer:number;unit:string;meaning:string;meaningOptions:string[];onPass?:()=>void}){const[value,setValue]=useState("");const[numericOk,setNumericOk]=useState(false);const[selected,setSelected]=useState("");const check=()=>setNumericOk(Math.abs(Number(value.replace(",","."))-answer)<.02);const choose=(x:string)=>{setSelected(x);if(x===meaning)onPass?.()};return <section className="before-continue"><b>PARA SE TË VAZHDOSH...</b><h3>{question}</h3><div className="inputline"><Input value={value} inputMode="decimal" onChange={e=>{setValue(e.target.value);setNumericOk(false);setSelected("")}}/><span>{unit}</span><Button onClick={check} disabled={!value}>Kontrollo</Button></div>{value&&!numericOk&&<small>Gjej ndryshimin mes gjendjes pas dhe para.</small>}{numericOk&&<><Feedback ok>Llogaritja është e saktë. Tani trego çfarë do të thotë.</Feedback><h4>Çfarë përfaqëson ky {answer} {unit}?</h4><div className="choices">{meaningOptions.map(x=><Button key={x} variant={selected===x?"default":"outline"} onClick={()=>choose(x)}>{x}</Button>)}</div>{selected&&<Feedback ok={selected===meaning}>{selected===meaning?"Saktë. Nuk gjete vetëm një numër, por një madhësi fizike.":"Kthehu te objekti dhe pyet: çfarë po zbulon diferenca?"}</Feedback>}</>}</section>}
export function Numeric({label,answer,unit,hints,onCorrect}:{label:string;answer:number;unit:string;hints:string[];onCorrect?:()=>void}){const[v,setV]=useState("");const[tries,setTries]=useState(0);const[done,setDone]=useState(false);const check=()=>{if(Math.abs(Number(v.replace(",","."))-answer)<.02){setDone(true);onCorrect?.()}else setTries(x=>x+1)};return <div className="numeric"><label>{label}</label><div><Input value={v} inputMode="decimal" onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==="Enter"&&check()} disabled={done}/><span>{unit}</span><Button onClick={check} disabled={!v||done}>{done?"U zgjidh":"Kontrollo"}</Button></div>{done?<Feedback ok>Saktë. E gjete me matje dhe llogaritje.</Feedback>:tries>0&&<Feedback>{hints[Math.min(tries-1,hints.length-1)]}</Feedback>}</div>}
export function Real({need,doit,observe,why}:{need:string;doit:string;observe:string;why:string}){const[open,setOpen]=useState(false);return <section className="real"><button onClick={()=>setOpen(!open)}><span><Beaker/> Provoje edhe në botën reale</span><ChevronRight/></button>{open&&<div>{[["Çfarë të duhet",need],["Çfarë të bësh",doit],["Çfarë të vëresh",observe],["Pse është interesante",why]].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div>}</section>}
export function Summary({items,badge,done,onDone,onNext}:{items:string[];badge?:string;done:boolean;onDone:()=>void;onNext:()=>void}){return <section className="summary"><div><b>SOT ZBULOVE</b><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul></div><aside>{badge&&<span>✦ ARRITJE<br/><strong>{badge}</strong></span>}<Button size="lg" onClick={done?onNext:onDone}>{done?"Misioni tjetër":"Përfundo misionin"}<ChevronRight/></Button></aside></section>}
